if not WeakAuras.IsLibsOK() then return end
---@type string
local AddonName = ...
---@class Private
local Private = select(2, ...)
Private.PatreonsList = {
  [=[007bb]=],
  [=[A]=],
  [=[Aaron Baska]=],
  [=[abdulla alsuwaidi]=],
  [=[Abeyance 702]=],
  [=[Adam Hedström]=],
  [=[Adam Večerka]=],
  [=[Adrian]=],
  [=[Adrian Dorobat]=],
  [=[adrian dziejma]=],
  [=[Adrien Le Texier]=],
  [=[ahnseungin]=],
  [=[Aigars Bedeicis]=],
  [=[AJ Lewis]=],
  [=[Alan Hill]=],
  [=[Alec Brennan]=],
  [=[Aleksandar Jovanovic]=],
  [=[Aleksandrs Šmagris]=],
  [=[Alena Mikhailova]=],
  [=[Alex Ripinskiy]=],
  [=[ali]=],
  [=[ali alkanderi]=],
  [=[ali alshemmari]=],
  [=[Am Queue]=],
  [=[Ande]=],
  [=[Andrew Theroux]=],
  [=[Anne Lydon Beaton]=],
  [=[Anne Smith]=],
  [=[Anthony]=],
  [=[Argent]=],
  [=[Armando]=],
  [=[Aspin]=],
  [=[Austin Chow]=],
  [=[Austin Judge]=],
  [=[B Tsang]=],
  [=[badbrain]=],
  [=[Bellular]=],
  [=[Ben]=],
  [=[Betsy]=],
  [=[Billy Earley]=],
  [=[BP]=],
  [=[Brett Staas]=],
  [=[Brian Heath]=],
  [=[Bryant]=],
  [=[Bryyzie Gaming]=],
  [=[Buds]=],
  [=[Bus]=],
  [=[Cameron Beer]=],
  [=[Cameron Linden]=],
  [=[Carter Navarro]=],
  [=[Casey Haynes]=],
  [=[Cat]=],
  [=[Causese]=],
  [=[Chace McLees]=],
  [=[Charilaos Skiadas]=],
  [=[Charles Cawley]=],
  [=[Chiel Kunkels]=],
  [=[Chris Hoffman]=],
  [=[Chris P. Bacon]=],
  [=[Christian Roth]=],
  [=[Christian Schneider]=],
  [=[Christopher Jansmann]=],
  [=[Christopher Mason]=],
  [=[Christopher Swoner]=],
  [=[Clem]=],
  [=[Clifford Kinney]=],
  [=[cody clark]=],
  [=[Colbi Anne]=],
  [=[Continuity]=],
  [=[DALE C RAMSEY]=],
  [=[Daniel Byrnes]=],
  [=[Danny Breton]=],
  [=[Darius Mazur]=],
  [=[Daryl Monge]=],
  [=[Dave Orlowski]=],
  [=[David Hughes]=],
  [=[David Maggs]=],
  [=[David Szabo]=],
  [=[David Waldroup]=],
  [=[DeAndre Jones]=],
  [=[Dennis]=],
  [=[Dennis Kato]=],
  [=[Derek Slenk]=],
  [=[dessie kinney]=],
  [=[Diana Tokarska]=],
  [=[Dick Ward]=],
  [=[DIMITRIOS KALDRYMIDIS]=],
  [=[Dinah McNutt]=],
  [=[dome barz]=],
  [=[domo_spb]=],
  [=[Doug Soule]=],
  [=[Drims]=],
  [=[Déb]=],
  [=[Elena]=],
  [=[Eliana Sanne]=],
  [=[elisabet Persson]=],
  [=[ELLJ itsatrap]=],
  [=[elloise611]=],
  [=[Eric DeLeon]=],
  [=[Eric Nordström]=],
  [=[Ernesto Navarro]=],
  [=[Espen Berg]=],
  [=[Eugene Fung]=],
  [=[Evgeny Soskov]=],
  [=[ExoBIS]=],
  [=[Faith Maceira]=],
  [=[Felinae]=],
  [=[Felix Schumacher]=],
  [=[Fiannor]=],
  [=[Frank Martin]=],
  [=[Gage Hughss]=],
  [=[Gerrit Alex]=],
  [=[Glenn Durfee]=],
  [=[Gray_Hound]=],
  [=[Greek]=],
  [=[Guido Schwarzer]=],
  [=[Guilherme Mossmann de Melo]=],
  [=[Gunther Birznieks]=],
  [=[heatho]=],
  [=[hEDCTOR]=],
  [=[Hekili]=],
  [=[hosni Djema]=],
  [=[icetiger]=],
  [=[Ifor]=],
  [=[Isak Johansson]=],
  [=[Itiba]=],
  [=[Jack Warner]=],
  [=[Jacob Hollenbeck]=],
  [=[James Michael Ash]=],
  [=[Jared Harmon]=],
  [=[Jason And Zac]=],
  [=[Jean Pierre Perales]=],
  [=[Jean Scheidegger]=],
  [=[Jeffrey Arthur Jones]=],
  [=[Jeremy Kirkindoll]=],
  [=[Jeremy Roughan]=],
  [=[Jeremy Visger]=],
  [=[Jesus Diaz]=],
  [=[jillatized]=],
  [=[Jiří Slováček]=],
  [=[John Vandervest]=],
  [=[Jonathan Jasinski]=],
  [=[Jonathan Massie]=],
  [=[Jordan Peterson]=],
  [=[Jorge Percheiro]=],
  [=[Joseph Champion]=],
  [=[Josh]=],
  [=[Josh]=],
  [=[Josh G]=],
  [=[Josh Wiley]=],
  [=[Joshua Prince]=],
  [=[Josiah Fuqua]=],
  [=[Joy Johnson]=],
  [=[Juha kovalainen]=],
  [=[Juho Liimatainen]=],
  [=[Julia F]=],
  [=[Junior Guevara]=],
  [=[Jury]=],
  [=[K]=],
  [=[Kameron Aimon Mangin]=],
  [=[Kanegasi]=],
  [=[Karina]=],
  [=[Kate Kornkven]=],
  [=[Kelly McWilliams]=],
  [=[ken]=],
  [=[Kendra Simes]=],
  [=[Kersti Rikka]=],
  [=[Kerwyn Brat]=],
  [=[Kevin Cappa]=],
  [=[Khaleel Alqallaf]=],
  [=[khalid almaadheed]=],
  [=[Kirill  Martynenko]=],
  [=[Konrad Polak]=],
  [=[Krazyito]=],
  [=[Kyle]=],
  [=[Kyle A Engle]=],
  [=[Lars Haupt-Hansen]=],
  [=[Linus Bourque]=],
  [=[Llordfaisall]=],
  [=[Luxthos]=],
  [=[Marcus Gaytan]=],
  [=[Mark]=],
  [=[Markus Vogelsang]=],
  [=[Martell Mignott]=],
  [=[Marvin Panzok]=],
  [=[Mason K Bailey]=],
  [=[Mathias Danielsen]=],
  [=[Mathieu Jules]=],
  [=[Matt Medoff]=],
  [=[matt penrod]=],
  [=[Matthew Fernandez]=],
  [=[Matthew Key]=],
  [=[MattJ]=],
  [=[Max Cristofori]=],
  [=[Max Dahlenborg]=],
  [=[Mazin Alzahrani]=],
  [=[Merfin]=],
  [=[Michael Kroupa]=],
  [=[Michael Roberts]=],
  [=[Michael Thomsen]=],
  [=[Mirrormn]=],
  [=[Mischael Schill]=],
  [=[Mitchell Savell]=],
  [=[Moowalker]=],
  [=[Mortis]=],
  [=[Muaadh Qureshi]=],
  [=[nan lin]=],
  [=[Nicholas D'Angelo]=],
  [=[Nicholas Jones]=],
  [=[Nicholas Lamoureux]=],
  [=[Nick Cohen]=],
  [=[Nick Hamilton]=],
  [=[Nick Herr Blumberg]=],
  [=[Nicky]=],
  [=[Nicolas Paterakis]=],
  [=[Nicolas Zuniga]=],
  [=[Oliver Ward]=],
  [=[Olly]=],
  [=[Ondřej Böhm]=],
  [=[panskii_]=],
  [=[Patches]=],
  [=[Paul Gubitz]=],
  [=[Paul Vurst]=],
  [=[Peaco]=],
  [=[Peter Davidsson]=],
  [=[Peter Day]=],
  [=[Peter Drayton]=],
  [=[peter gaming]=],
  [=[philip]=],
  [=[qtrpally@gmail.com]=],
  [=[Rachel Chaimson]=],
  [=[Rainer Bieniek]=],
  [=[ravenskull Arntsen]=],
  [=[Ray Fisher]=],
  [=[Richard]=],
  [=[Robby Allbritton]=],
  [=[Roman Haag]=],
  [=[Ruben Miguel Fores]=],
  [=[Ryan Mcdonald]=],
  [=[S]=],
  [=[Sam]=],
  [=[Sam Strömerstén]=],
  [=[Sascha Rudnicki]=],
  [=[Scott Edwards-Dohn]=],
  [=[Scott Ingram]=],
  [=[Seenia]=],
  [=[Sergio Ceja]=],
  [=[Seriallos]=],
  [=[Serox Zidane]=],
  [=[shaikh amjad]=],
  [=[Shalais]=],
  [=[Shannon Marshall]=],
  [=[Shaun]=],
  [=[Shelby Smith]=],
  [=[Sid]=],
  [=[Simon Posner]=],
  [=[Stefan]=],
  [=[Stefan]=],
  [=[Steve Giggity]=],
  [=[steve greenberg]=],
  [=[Steve Román]=],
  [=[Steven Parsons]=],
  [=[sus]=],
  [=[Susan Mushill]=],
  [=[Swealer]=],
  [=[Taliesin and Evitel Do Games]=],
  [=[Talion]=],
  [=[Taylor Davis]=],
  [=[Ted Vurbeff]=],
  [=[Therapy]=],
  [=[Theresa Cobb]=],
  [=[Thomas Garcia]=],
  [=[Thomas Niven]=],
  [=[Thomas pope]=],
  [=[Thorill]=],
  [=[Tilr]=],
  [=[Tim Foresee]=],
  [=[tim Hadley]=],
  [=[todd freeman]=],
  [=[Trucidar]=],
  [=[Truong Cao]=],
  [=[Turtvaiz]=],
  [=[Tyler Daughety]=],
  [=[vasko]=],
  [=[Vaughn Hornberger]=],
  [=[Velsenard]=],
  [=[Waggz]=],
  [=[Wander Koldewijn]=],
  [=[William Mason]=],
  [=[William swearengin]=],
  [=[WriterFluff]=],
  [=[Yavor Marinov]=],
  [=[Yiduo Hao]=],
  [=[Yoshi Petit]=],
  [=[yousef]=],
  [=[Yubo Chen]=],
  [=[Zach Tittle]=],
  [=[Zach Tittle]=],
  [=[ZaffronStaghelm]=],
  [=[zeyad almohammadi]=],
  [=[Zlappo]=],
}
Private.PatreonsListCJ = {
  [=[灵魂复苏SoulAwaken]=],
}
Private.PatreonsListK = {
  [=[상헌 이]=],
  [=[찬인 박]=],
}
