if not WeakAuras.IsLibsOK() then return end
---@type string
local AddonName = ...
---@class Private
local Private = select(2, ...)
Private.PatreonsList = {
  [=[007bb]=],
  [=[A]=],
  [=[Abeyance 702]=],
  [=[Adam Hedström]=],
  [=[Adam Večerka]=],
  [=[Adrian]=],
  [=[AJ Lewis]=],
  [=[Alan Hill]=],
  [=[Alec Brennan]=],
  [=[Aleksandar Jovanovic]=],
  [=[Alena Mikhailova]=],
  [=[ali alshemmari]=],
  [=[Am Queue]=],
  [=[Ande]=],
  [=[Anne Lydon Beaton]=],
  [=[Argent]=],
  [=[Armando]=],
  [=[Aspin]=],
  [=[Austin Chow]=],
  [=[Austin Judge]=],
  [=[B Tsang]=],
  [=[badbrain]=],
  [=[Bellular]=],
  [=[Ben]=],
  [=[Betsy]=],
  [=[BP]=],
  [=[Buds]=],
  [=[Burlis]=],
  [=[Cameron Beer]=],
  [=[Cameron Linden]=],
  [=[Carter Navarro]=],
  [=[Casey Haynes]=],
  [=[Causese]=],
  [=[Chab]=],
  [=[Chace McLees]=],
  [=[Charilaos Skiadas]=],
  [=[Chiel Kunkels]=],
  [=[Chris P. Bacon]=],
  [=[Christian Schneider]=],
  [=[Clem]=],
  [=[cody clark]=],
  [=[Colbi Anne]=],
  [=[Continuity]=],
  [=[DALE C RAMSEY]=],
  [=[Danny Breton]=],
  [=[Darius Mazur]=],
  [=[Daryl Monge]=],
  [=[Dave Orlowski]=],
  [=[David Hughes]=],
  [=[David Maggs]=],
  [=[David Waldroup]=],
  [=[DeAndre Jones]=],
  [=[Dennis Kato]=],
  [=[Derek Slenk]=],
  [=[Dick Ward]=],
  [=[DIMITRIOS KALDRYMIDIS]=],
  [=[dome barz]=],
  [=[Doug Soule]=],
  [=[elisabet Persson]=],
  [=[elloise611]=],
  [=[Eric DeLeon]=],
  [=[Eric Nordström]=],
  [=[Ernesto Navarro]=],
  [=[Exality]=],
  [=[Faith Maceira]=],
  [=[Fatpala]=],
  [=[Felinae]=],
  [=[Felix Schumacher]=],
  [=[Fiannor]=],
  [=[Frank Martin]=],
  [=[Gage Hughss]=],
  [=[Gerrit Alex]=],
  [=[Glenn Durfee]=],
  [=[Gray_Hound]=],
  [=[Guido Schwarzer]=],
  [=[Gunther Birznieks]=],
  [=[heatho]=],
  [=[Hekili]=],
  [=[hosni Djema]=],
  [=[icetiger]=],
  [=[Ifor]=],
  [=[Jacob Hollenbeck]=],
  [=[James Michael Ash]=],
  [=[Jared Harmon]=],
  [=[Jason And Zac]=],
  [=[Jean Pierre Perales]=],
  [=[Jeremy Visger]=],
  [=[Jesus Diaz]=],
  [=[jillatized]=],
  [=[John Vandervest]=],
  [=[Jonathan Jasinski]=],
  [=[Jonathan Massie]=],
  [=[Jordan Peterson]=],
  [=[Joseph Champion]=],
  [=[Josh]=],
  [=[Josh]=],
  [=[Josh Wiley]=],
  [=[Joshua Prince]=],
  [=[Joy Johnson]=],
  [=[Juha kovalainen]=],
  [=[Julia F]=],
  [=[Jury]=],
  [=[K]=],
  [=[Kameron Aimon Mangin]=],
  [=[Kanegasi]=],
  [=[Karina]=],
  [=[Kate Kornkven]=],
  [=[Kelly McWilliams]=],
  [=[ken]=],
  [=[Kersti Rikka]=],
  [=[Kerwyn Brat]=],
  [=[Kevin Cappa]=],
  [=[Krazyito]=],
  [=[Kyle]=],
  [=[Kyle A Engle]=],
  [=[Lars Haupt-Hansen]=],
  [=[Linus Bourque]=],
  [=[Listefano]=],
  [=[Luxthos]=],
  [=[Markus Vogelsang]=],
  [=[Mason K Bailey]=],
  [=[Mathias Danielsen]=],
  [=[Matt Medoff]=],
  [=[Matthew Fernandez]=],
  [=[Matthew Key]=],
  [=[MattJ]=],
  [=[Max Cristofori]=],
  [=[Max Dahlenborg]=],
  [=[Merfin]=],
  [=[Michael Kroupa]=],
  [=[Michael Roberts]=],
  [=[Mirrormn]=],
  [=[Mischael Schill]=],
  [=[Mitchell Savell]=],
  [=[Moowalker]=],
  [=[Muaadh Qureshi]=],
  [=[nan lin]=],
  [=[Nicholas Jones]=],
  [=[Nick Cohen]=],
  [=[Nick Hamilton]=],
  [=[Nick Herr Blumberg]=],
  [=[Nicky]=],
  [=[Nicolas Zuniga]=],
  [=[Olly]=],
  [=[Ondřej Böhm]=],
  [=[Patches]=],
  [=[Paul Vurst]=],
  [=[Peter Davidsson]=],
  [=[Peter Day]=],
  [=[Peter Drayton]=],
  [=[Rachel Chaimson]=],
  [=[Rainer Bieniek]=],
  [=[ravenskull Arntsen]=],
  [=[Robby Allbritton]=],
  [=[Roman Haag]=],
  [=[Ryan Mcdonald]=],
  [=[S]=],
  [=[Sam Strömerstén]=],
  [=[Scott Edwards-Dohn]=],
  [=[Scott Ingram]=],
  [=[Sergio Ceja]=],
  [=[Seriallos]=],
  [=[Shalais]=],
  [=[Shannon Marshall]=],
  [=[Shaun]=],
  [=[Shelby Smith]=],
  [=[Sid]=],
  [=[Stefan]=],
  [=[steve greenberg]=],
  [=[Steve Román]=],
  [=[Steven Parsons]=],
  [=[sus]=],
  [=[Swealer]=],
  [=[Taliesin and Evitel Do Games]=],
  [=[Talion]=],
  [=[Taylor Davis]=],
  [=[Ted Vurbeff]=],
  [=[Therapy]=],
  [=[Theresa Cobb]=],
  [=[Thomas Niven]=],
  [=[Thorill]=],
  [=[Tilr]=],
  [=[tim Hadley]=],
  [=[todd freeman]=],
  [=[Trucidar]=],
  [=[Truong Cao]=],
  [=[Turtvaiz]=],
  [=[Vaughn Hornberger]=],
  [=[Velsenard]=],
  [=[Waggz]=],
  [=[William Mason]=],
  [=[Wizeowel]=],
  [=[WriterFluff]=],
  [=[Yavor Marinov]=],
  [=[Yiduo Hao]=],
  [=[yousef]=],
  [=[ZaffronStaghelm]=],
  [=[Zlappo]=],
}
Private.PatreonsListCJ = {
  [=[灵魂复苏SoulAwaken]=],
}
Private.PatreonsListK = {
  [=[상헌 이]=],
}
