name: Create Atlas file list update pull request

on:
  schedule:
    - cron:  '0 10 * * *'

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  atlasUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10

      - name: Update Atlas files from wago.tools
        run: |
          cd .github/scripts/
          ./wagotools-atlas.sh
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-atlasfiles
          commit-message: Update atlas file list from wago.tools
          title: Update atlas file list from wago.tools
          delete-branch: true
